community/urls.py
from django.urls import path
from community import views
# from user import User

app_name = 'community'

urlpatterns = [
    path('', views.board)
]

turtle_main/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('community/', include('community.urls')),
]

user/urls.py
from django.urls import path
from user import views

app_name = 'user'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('index/', views.index, name='index')
]

community/models.py
from django.db import models
from user.models import User
from django.contrib.auth.models import AbstractBaseUser

class Article(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return str(self.title)

user/models.py
# from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    class Meta:
        db_table = 'turtles_user'

community/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Article
# Create your views here.

def board(request):
    articles = Article.objects.all()
    context={
        'articles': articles
    }
    return render(request, 'board.html', context)

user/views.py
from django.shortcuts import render,redirect
from .models import User
from django.contrib.auth import authenticate
from django.contrib.auth import login as login1

# Create your views here.
def signup(request):
    if request.method == 'GET':
        return render(request, 'signup.html')

    if request.method == 'POST':
       username = request.POST.get('username')
       password = request.POST.get('password')
       passwordcheck = request.POST.get('passwordcheck')
       if password == passwordcheck:
        User.objects.create_user(username=username, password=password)
        return redirect('user:login')

def login(request):
    if request.method == 'GET':
        return render(request, 'login.html')

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username,password=password)
        if user is not None:
            login1(request,user)
            print("로그인성공")
            return redirect('user:index')
        else:
            print("로그인실패")
            return redirect('user:login')

def index(request):
    if request.method == 'GET':
        return render(request, 'index.html')

community/templates/board.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>board 게시글페이지</title>
</head>
<body>
    <h1>모든 게시글들</h1>
    {% for article in articles %}
    <div>
        <h3>{{ article.title }}</h3>
        <p>{{ article.content }}</p>
        <p>{{ article.created_at }}</p>
    </div>

    {% endfor %}
    

</body>
</html>

user/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>로그인 성공</h1>
</body>
</html>

user/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>로그인페이지 입니다.</h1>
    <form action="{% url 'user:login' %}" method="POST">
        {% csrf_token %}
        <input type="text" name="username">
        <input type="text" name="password">
        <input type="submit" value="로그인">
    </form>
</body>
</html>

user/templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>회원가입 페이지 입니다.</h1>
    <form action="{% url 'user:signup' %}" method="POST">
        {% csrf_token %}
        <input type="text" name="username">
        <input type="text" name="password">
        <input type="text" name="passwordcheck">
        <input type="submit" value="가입">
    </form>
    
</body>
</html>